spring:
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 127.0.0.1 # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      password: 123456abcdef # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接
  mail: # 新增邮件配置
    host: smtp.qq.com
    port: 465
    username: 2861173454@qq.com
    password: tefabikvpxhpdeff # SMTP授权码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true # 启用SSL
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



aliyun: # 接入阿里云（发送短信使用）
  accessKeyId: LTAI5t8RRoBvPx4Cc4rkcMDU # 改成你自己的
  accessKeySecret: gfKiyIXhmpPzXK6sS51saOJ0oW9Nn6 # 改成你自己的






